name: SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Install Maven 4.0.0-rc-2
      run: |
        curl -sL https://archive.apache.org/dist/maven/maven-4/4.0.0-rc-2/apache-maven-4.0.0-rc-2-bin.tar.gz | tar xz
        sudo mv apache-maven-4.0.0-rc-2 /opt/maven
        echo "MAVEN_HOME=/opt/maven" >> $GITHUB_ENV
        echo "/opt/maven/bin" >> $GITHUB_PATH


    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: SonarQube Scan
      env:
        sonar-token: ${{ secrets.SONAR_TOKEN }}  # Token de SonarQube
      run: |
         mvn sonar:sonar \
          -Dsonar.host.url=http://44.202.202.62:9000 \
          -Dsonar.login=$SONAR_TOKEN

    - name: Run tests
      run: mvn test

    - name: Run tests (CI profile)
      run: mvn test -P ci

